language: node_js
node_js:
  stable
cache:
  directories:
    node_modules
before_deploy:
  npm run build
deploy:
  provider: firebase
  token:
    secure: "jBcmileFD8JEZNCr91JqiH5p9oYZ3DAq5wn8nmChts2f1SmGgCq1ezo2dcIliPrCuIR9BjxBu6DkyYBq5Rw+VwXSqaACmROH0GHHOHVGDDbuhvmDRzIUi1VLRxNSXWwzvHQhtqH+c/DankLJ7PTZIl2aAqTBuA0tNUCNF/NmeLjehqHAqoQhGNIbrlUG1GIfzAc1TxkePyf3ESqMfWgNQK1Sa4fyNLNg7g3duebjjw3xoACuRoinmNgajOhGq71yT57AFoij9sLrxwW9nMmm+/zkPLMy1VfFIcttJ5Kyn0fyqNQRrC1usqJx5ts3onYAK5j/6tArAzhEt7zywXfKoJn/DMBeDf961KaB7flxAua1AdnF0Eu94Lzz7eP+CcxDdJNHoUZyCgKu0XIZR81yl0UH2Z0V2Zl7hU9x/JMONqpDcYUudumwqoh2dWih4i02nDDc0gqQ7gIYKMsNoWDgYB1x8p+t3kDzM7Wt1Pp5D1F7eoMAwI+yfve8W44oNNp6O1KwXseBPTbKpOeGEoZv2TKBPq8PvNUIjtZQXVteKbT+y+TvgTgheMMkiHo4tFk+buLjbVJcxI6aHTQkGkClmd4+WBj9VT8FtHGdSZM27dwKGkHM0R41wVUO/Qrk7CSNdwqOi8ujNryk/YSI0y359cy3SSdJdpO9k1Eo6i/KF68="